### ISSUE TITLE
rqt_controller_manager stuck

### ISSUE THREAD

**Issue by daBaret** [ros-controls/ros2_control#2415]
**Describe the bug**
The rqt_controller_manager plugin is unusable after a few seconds is running. The UI becomes unresponsive and it gets stuck. The function `_update_controllers` seem to take increasingly more time to execute. At some point it takes more time than the Timer and it gets very slow. Here you can see the execution time increasing:

<img width="637" height="592" alt="Image" src="https://github.com/user-attachments/assets/561e3fcf-42c3-4f07-ae70-c3e1c624dc87" />

**To Reproduce**
1. `ros2 run rqt_controller_manager rqt_controller_manager`
2. Wait ca. 10-20 seconds
3. Try any operation on the gui

**Environment (please complete the following information):**
 - OS: Ubuntu 24.04 (Docker container)
 - Version Jazzy

Thank you for your great work!

**Comment by christophfroehlich** [comment]
@daBaret does the problem still exist?

**Comment by daBaret** [comment]
Hi @christophfroehlich. Yes, it still happens

**Comment by christophfroehlich** [comment]
Is the system (ros2_control_node) still running? I often have problems when I restart the node, then the ROS API of the service call stucks, which makes rqt_cm stuck soon. This should be fixed, but when I had a look last time there was no built-in timout of the python service call of rclpy.

**Comment by sbstorz** [comment]
From my experience the issue persists. The ros2_control_node has been running constantly.
I have removed/commented the following lines:

 https://github.com/ros-controls/ros2_control/blob/b3075dc13a2d505ebfb1d43459afab9ca59ec9a6/rqt_controller_manager/rqt_controller_manager/controller_manager.py#L204-L210

This way it takes a longer time until the rqt_cm gets stuck but it still does after a few minutes, bringing down the entire OS.

On another note, I have a panel plugin for RViz, in which I subscribe to _/~/activity_ and use the _~/set_hardware_component_state_, _/~/switch_controller_, _/~/configure_controller_ services, also here after a while (a few minutes) the Rviz frame rate drops to close to zero and Rviz consumes all CPU. If I close the panel, RViz recovers. (I am not 100% certain as this can obviously also another bug in my code but the symptoms are very similar)

Ubuntu 24.04 in WSL2 on Windows
rqt_controller_manager: Jazzy 4.38.0

**Comment by christophfroehlich** [comment]
I can't reproduce this with jazzy or rolling version, both compiled from source and default RMW. Do you have a different RMW selected?
Can you test to compile the jazzy version and/or the rolling development version [from sourc](https://control.ros.org/jazzy/doc/getting_started/getting_started.html#building-from-source), and test again?
